# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-02-04 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180203_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asifurl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
